### PR TITLE
feat(azure): Azure Cloud Storage(Blobs) for Kayenta.

### PR DESCRIPTION
**Pull request by amsin02**
Kayenta Currently supports S3/GCS/Minio as persistent storage.

We are adding Azure Blobs as well to act as Kayenta's OBJECT_STORE and CONFIGURATION_STORE.

### CODE REVIEW

**Comment by amsin02** [comment]
Hi @fieldju, @skandragon, @duftler 

Can you please review my PR.

**Comment by fieldju** [comment]
@amsin02 We all live in America and we are on vacation more or less until Monday.

I will check this out then.

A couple quick comments.

1. Rebase your commits and follow the conventional commits messaging.
2. All of your files need the Apache 2.0 license header with your org and current year in them.
3. Follow the code style of the project
image

image

Curly braces at end of line, no extraneous white space at end of files, etc

**Comment by fieldju** [comment]
@amsin02 waiting on you to make the style guide changes and update the license headers.

**Comment by nishubansal** [comment]
@fieldju I will be making code changes to this PR. I will update it as per your comments.

**Comment by nishubansal** [comment]
@fieldju @skandragon @duftler - Please review this PR https://github.com/spinnaker/kayenta/pull/587 it has all the changes as per PR comments.

**Comment by fieldju** [comment]
Closing in favor of:  #587

**Pull request closed without merging**
