### PR TITLE
feat(*): Github Actions for PR builds

### PR DESCRIPTION
**Pull request by ajordens**

### CODE REVIEW

**Comment by fieldju** [comment]
Would still like the functional tests to run in CI
https://github.com/spinnaker/kayenta/blob/master/.travis.yml#L14

**Comment by ajordens** [comment]
Oh interesting ... that's non-standard but I'll add the same env variable.

**Comment by fieldju** [comment]
Does this PR trigger the action or does it have to be merged and then it works with future PRs?
I was going to try to look at the logs and make sure all that docker stuff for the functional tests still works in the new CI env.

**Comment by ajordens** [comment]
I think it'll have to merge first and then it'll run on future PRs.

This isn't taking away TravisCI builds (and we'll still be relying on a 👍 from it).

**Pull request merged**
