### PR TITLE
chore(builds): Reformat spinnaker deps version

### PR DESCRIPTION
**Pull request by ttomsu**
The deps as 'XXX' seems a bit troubling... How does this currently work, @duftler ?

### CODE REVIEW

**Comment by ttomsu** [comment]
@duftler - Can you grant our team write access to this repo as well?

**Comment by duftler** [comment]
Will have to ask @skandragon why this differs from the other Spinnaker services w.r.t. specifying the spinnaker deps version (note that it appears to be set here: https://github.com/spinnaker/kayenta/blob/master/gradle.properties#L3)

**Comment by duftler** [comment]
Looks like this PR shouldn't be merged until the discrepancy is resolved.

**Comment by ttomsu** [comment]
Ping

**Comment by ttomsu** [comment]
I'm going to push ahead with this change. If it breaks anything, please let me know.

**Pull request merged**
