### PR TITLE
chore(builds): Introduces composite builds via gradle plugin

### PR DESCRIPTION
**Pull request by ttomsu**
Removes spring boot gradle plugin. 

Ref: https://github.com/spinnaker/spinnaker/issues/2844

### CODE REVIEW

**Comment by fieldju** [comment]
The SignalFx integration tests still pass.

I noticed this change eliminates the ability to create a fatJar via `./gradlew bootRepackage -DspringBoot.repackage=true` is there an alternative way to create the fatJar?

**Comment by duftler** [comment]
I don't know the answer to that question. Maybe @ttomsu or @cfieber know.

**Comment by cfieber** [comment]
@fieldju the gradle upgrade includes removal of the spring-boot plugin. If you do want to package a fatjar you could look at creating an init-script to include (similar to what we are doing when publishing is enabled via `-I gradle/init-publish.gradle`)

**Comment by fieldju** [comment]
Makes perfect sense, the init script should do the trick, thanks.

**Pull request merged**
