### PR TITLE
fix(templates): Escape custom inline templates.

### PR DESCRIPTION
**Pull request by duftler**

### CODE REVIEW

**Comment by jmccann** [comment]
@duftler Thanks a ton for looking into this.

Using this patch I'm still seeing the same issue.

Here is what I'm doing to reproduce.  I've tried to setup https://github.com/jmccann/kayenta/tree/kayenta-fail-demo to help automate reproducibility.  I apologize if I baby step this too much.

1. Start up kayenta standalone
    * start a local redis instance on `localhost:6379`
    * Using sample [kayenta.yml](https://github.com/jmccann/kayenta/blob/kayenta-fail-demo/demo/kayenta.yml) with your own prom instance url
    * Putting my `kayenta.yaml` in `~/.spinnaker/kayenta.yaml`
    * Starting kayenta with `./gradlew build && ./gradlew -DDEBUG=true`
2. `POST /standalone_canary_analysis` with [sample payload](https://github.com/jmccann/kayenta/blob/kayenta-fail-demo/demo/should-work.json)
    * If using my branch can do `demo/post-canary.sh demo/should-work.json`
    * May need to adjust query for your prom metrics, main thing is to include `${scope}` and/or `${location}` in it

You will then see almost immediately in logs:

```
2019-06-28 07:50:37.923  INFO 38715 --- [    scheduler-9] com.netflix.spinnaker.q.QueueProcessor   : Received message StartExecution(executionType=pipeline, executionId=01DEF26F0RRE73SBHPHCGQQY9M, application=examplecanarymicroservice)
2019-06-28 07:50:38.001  INFO 38715 --- [    scheduler-9] com.netflix.spinnaker.q.QueueProcessor   : Received message StartStage(executionType=pipeline, executionId=01DEF26F0RRE73SBHPHCGQQY9M, application=examplecanarymicroservice, stageId=01DEF26F0STT40ZWBCV8MWJSE4)
2019-06-28 07:50:38.031  INFO 38715 --- [     handlers-2] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 07:50:38.043  INFO 38715 --- [     handlers-2] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 07:50:38.104  INFO 38715 --- [     handlers-2] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 07:50:38.115  INFO 38715 --- [     handlers-2] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 07:50:38.122  INFO 38715 --- [     handlers-2] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
```

Then after first waiting period it will go terminal even though it successfully went to fetch the metrics as expected from prom:

```
2019-06-28 07:51:38.847  WARN 38715 --- [    handlers-19] c.n.s.okhttp.OkHttpMetricsInterceptor    : Request GET:http://your.prom.url/api/v1/query_range?query=sum%28irate%28status%7Bcode%3D%22404%22%2C+kubernetes_namespace%3D%22prod-namespace%22%2C+kubernetes_name%3D%22our-experiment%22%7D%5B5m%5D%29%29&start=2019-06-28T12%3A50%3A38.080208Z&end=2019-06-28T12%3A51%3A38.080208Z&step=10 is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
2019-06-28 07:51:38.847  WARN 38715 --- [    handlers-20] c.n.s.okhttp.OkHttpMetricsInterceptor    : Request GET:http://your.prom.url/api/v1/query_range?query=sum%28irate%28status%7Bcode%3D%22404%22%2C+kubernetes_namespace%3D%22prod-namespace%22%2C+kubernetes_name%3D%22our-control%22%7D%5B5m%5D%29%29&start=2019-06-28T12%3A50%3A38.080208Z&end=2019-06-28T12%3A51%3A38.080208Z&step=10 is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
```

3. You can then grab the status from `GET /standalone_canary_analysis` using provided `canaryAnalysisExecutionId` from step 2 and see it went `terminal` from `Failed Expression Evaluation`
    * `demo/get-canary-status.sh <canaryAnalysisExecutionId>`

**Comment by duftler** [comment]
>  I apologize if I baby step this too much.

No, this is great. Will work through your example now.

**Comment by duftler** [comment]
Was able to reproduce. Thanks @jmccann!

**Comment by duftler** [comment]
Found the trouble. Please try it again when you have a chance.

**Comment by jmccann** [comment]
@duftler Thanks!  Will try it now.

**Comment by jmccann** [comment]
@duftler I rebased off your branch and do see a change in behaviors:

* now is there are *less* instances of `Evaluated 1 expression(s) ... 1 failed` ... from 5 in my above comment to 2 now:
```
2019-06-28 09:10:30.410  INFO 55097 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : Received message StartExecution(executionType=pipeline, executionId=01DEF6RQBZBGV5283B20DM1C9T, application=examplecanarymicroservice)
2019-06-28 09:10:30.421  INFO 55097 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : Received message StartStage(executionType=pipeline, executionId=01DEF6RQBZBGV5283B20DM1C9T, application=examplecanarymicroservice, stageId=01DEF6RQBZXTPB7PA6Z745B5K0)
2019-06-28 09:10:30.422  INFO 55097 --- [    handlers-20] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 09:10:30.423  INFO 55097 --- [    handlers-20] c.n.s.o.p.u.ContextParameterProcessor    : Evaluated 1 expression(s) - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m]))), 1 failed - (PromQL:sum(irate(status{code="404", kubernetes_namespace="prod-namespace", kubernetes_name="scope"}[5m])))
2019-06-28 09:10:30.432  INFO 55097 --- [    scheduler-4] com.netflix.spinnaker.q.QueueProcessor   : Received message StartStage(executionType=pipeline, executionId=01DEF6RQBZBGV5283B20DM1C9T, application=examplecanarymicroservice, stageId=01DEF6RQCQ0RX6XRRGQEH8WXDJ)
```
* if metrics are "happy" (experiment is passing according to metrics) it now works
* if metrics are "unhappy" (experiment is failing according to metrics) it gives the same `Failed Expression Evaluation` message ... I'd expect the exception to be some other message that metrics are not good to proceed (hope this made sense ...)

So it seems your update fixed most of the issues but there is another spot that needs the escaping?

**Comment by duftler** [comment]
I think I know what that final expression evaluation issue is. I didn't escape the spot where it transforms the execution for the purposes of returning the result. That's likely the source of those messages. Let me look at that now.

**Comment by duftler** [comment]
@jmccann One more lap around the park, please. I've confirmed that that no `Evaluated 1 expression(s) ... 1 failed` messages are logged now, and that the `Failed Expression Evaluation` message does not appear in the result.

**Comment by jmccann** [comment]
@duftler testing it now!

**Comment by jmccann** [comment]
@duftler 🎊 its working 🎊 

Thanks a ton!

**Comment by duftler** [comment]
Sweet!

**Comment by maggieneterval** [comment]
@spinnakerbot cherry-pick 1.14

**Pull request merged**
