### PR TITLE
Fixes content-type in error response for IllegalArgumentException

### PR DESCRIPTION
**Pull request by Aloren**
- error response now is sent in json format

Relates to #419

### CODE REVIEW

**Comment by Aloren** [comment]
@skandragon could you please review the changes? Thanks

**Comment by fieldju** [comment]
@duftler,

I am in favor of merging this.
This will make the mime-types of Kayenta responses consistent (application/json).

This is technically a breaking API change though, and I am not sure what the consequences of this change would be to existing integrations.

I still want to do a spike later on Backstopper for Request validation and error handling and see that pattern would be nice and work with this code base.

**Comment by skandragon** [comment]
@duftler Do you see any reason that deck-kayenta would need to be changed for this to be merged?  It seems likely it will just work, and feels like a good change.

**Comment by duftler** [comment]
The changes look good to me, but might be worth running orca against it and confirming that orca can still propagate the returned exception properly. I'm sure deck-kayenta just renders what orca returns, so the question is if orca needs to be changed.

**Pull request merged**
