### PR TITLE
refactor(judge): remove isDataRequired field from MetricClassification

### PR DESCRIPTION
**Pull request by Aloren**
This field was introduced in #421, but it is never set and never used anywhere.

### CODE REVIEW

**Comment by fieldju** [comment]
https://github.com/Nike-Inc/kayenta/blob/8c700e66fdec052e0c29345510031773cf538636/kayenta-judge/src/main/scala/com/netflix/kayenta/judge/classifiers/metric/MannWhitneyClassifier.scala#L139

**Comment by fieldju** [comment]
This field is used to determine when a metric should fail because it has no data and data is required.

**Comment by fieldju** [comment]
I was having issues with my web browser, this should be fine.

**Comment by fieldju** [comment]
Will merge once the build finishes, had to merge master in.

**Comment by csanden** [comment]
Just to clarify for future reference, the `isDataRequired` field is not used as part of the `MetricClassification` result, i.e., what the metric classifiers return. However, there is a `isDataRequired` parameter as part of the  `classify` method on the `BaseMetricClassifier` which is still used.

**Pull request merged**
