### PR TITLE
feat(Azure): Azure cloud storage(Blobs) support added for Kayenta

### PR DESCRIPTION
**Pull request by nishubansal**
Kayenta Currently supports S3/GCS/Minio as persistent storage.
We are adding Azure Blobs as well to act as Kayenta's OBJECT_STORE and CONFIGURATION_STORE.

### CODE REVIEW

**Comment by fieldju** [comment]
Hey @nishubansal,

Thanks for updating that branch / making this PR.

I still see some code style issues with this branch, however good news on this. 
It is now automated, once you rebase master into this branch (again, I know you just did that, but all the pending PRs just got merged into master including the code style automation).

- [ ] Rebase master into this branch, and run `./gradlew spotlessApply` this will auto format the code to follow the Spinnaker style guide.

I glanced through the code, and I am not seeing anything that stood out, I was going to user acceptance test this but I am waiting for access to Azure, my team coincidently is doing a spike or 2 into some Azure stuff. 

Have you user acceptance tested this code and confirmed that it works as intended?

- [ ] Sanity check that this integration works as intended.

The way I was going to user acceptence check this was to manually modify https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/integration-test/resources/config/kayenta.yml to use this integration instead of the in-mem store and run the SignalFx integration tests

```bash
./gradlew kayenta-signalfx:integrationTest -Dkayenta.signalfx.apiKey=${SIGNALFX_API_TOKEN} -Dredis.path=$(which redis-server)
``` 
Then verify that files were being written and that everything is happy.

**Comment by nishubansal** [comment]
@fieldju - Yes we have done integration tests for this. Code just works. Also as per your suggestion, I have updated the PR with master changes and ran gradlew spotlessApply task.

**Comment by fieldju** [comment]
I am not sure why the bot didn't comment on this PR, but can you check out this comment from the other PR and update this PR to follow the commit message convention and I can work on getting this merged Monday.

https://github.com/spinnaker/kayenta/pull/586#issuecomment-511711535

**Comment by nishubansal** [comment]
@fieldju done. I have updated the commit message.

**Pull request merged**
